### ISSUE TITLE
app_store: more informative errors

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#128]
It would be nice for app_store to give more information to devs upon error. One simple way to do this would be to make the `Failure` cases have a String and string-ify the Rust Error, e.g.

https://github.com/uqbar-dao/uqbar/blob/7cef9e48577078f044732e3ceb34465ab8fdcd2e/modules/app_store/app_store/src/lib.rs#L131

to
```
Failure(String),
```

and

https://github.com/uqbar-dao/uqbar/blob/7cef9e48577078f044732e3ceb34465ab8fdcd2e/modules/app_store/app_store/src/lib.rs#L300

to

```
Err(e) => LocalResponse::NewPackageResponse(NewPackageResponse::Failure(format!("{}", e))),
```

**Comment by dr-frmr** [comment]
The rewrite in #205 will resolve this
