### ISSUE TITLE
terminal: backspace erases wrong character when line is wrapped

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#129]
If in a horizontally-constrained window and editing a long command line, pressing Backspace erases the wrong character.

**Comment by nick1udwig** [comment]
Also seems that inputs can go in the wrong place sometimes:

https://discord.com/channels/1186394868336038080/1186421052071477428/1255594346284187750

**Comment by dr-frmr** [comment]
pretty sure this doesn't happen anymore
