### ISSUE TITLE
correct all compiler warnings

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#177]
Currently you get spammed with a lot of warnings on build. The spam makes this feature of the compiler useless, since you get inured to the text scroll. As a result, new warnings get lost in the noise.

**Comment by dr-frmr** [comment]
note: there is only one warning in the no-features build. the loads of warnings come from the simulation-mode feature which makes all the `net` code unused. we can add an `allow_unused` behind the feature to resolve

**Comment by nick1udwig** [comment]
Interesting -- I'll fix that next week.

**Comment by nick1udwig** [comment]
There are still a couple, but I'll close this for now.
