### ISSUE TITLE
app_store: use the new file_transfer worker?

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#235]
https://github.com/bitful-pannul/file_transfer implements a new worker for transferring files. We should probably use one of these and focus efforts on making it as good & robust as possible and point people to use it for their apps that need to transfer files.

**Comment by nick1udwig** [comment]
Why not planned?

**Comment by nick1udwig** [comment]
@dr-frmr Bump, what's the deal here, why is this not planned? This seems like it would be a win to me.

**Comment by nick1udwig** [comment]
Reopening because we've agreed it'd be nice to use this or a similar worker in app_store

**Comment by dr-frmr** [comment]
@bitful-pannul has now done this in #472

**Comment by nick1udwig** [comment]
The code looks better than before (i.e. we don't read the entire file into memory, so that's good!). But its not the same as the userspace file transfer.

Its not obvious to me why we aren't using the same code here. Maybe we should discuss this in an upcoming meeting so I can understand the decision @bitful-pannul ?
