### ISSUE TITLE
terminal: pasting causes cursor to go to end of line

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#259]
E.g. imagine I have a line

```
foo baz
```

and I have my cursor on the space and `bar ` in the clipboard. Pasting will properly modify the line, but will move my cursor to the end (i.e. to the `z` in `baz`), rather than, as expected, the end of the paste (the space in `bar `).

**Comment by nick1udwig** [comment]
FYI @tadad @dr-frmr (not sure who owns this part of terminal).

**Comment by dr-frmr** [comment]
fixed in `develop`!
