### ISSUE TITLE
feature: build instructions for Linux

### ISSUE THREAD

**Issue by hjorthjort** [uqbar-dao/nectar#262]
**Is your feature request related to a problem? Please describe.**
The build steps in the Readme and gitbook doesn't outline some of the depenencies necessary to build Kinode from source on Linux systems.

**Describe the solution you'd like**
Add explicitly dependecies that need to be installed, and links to where to obtain them.

**Describe alternatives you've considered**
Linux users may be assumed to be able to figure this out on their own but a heads-up helps and reduces time to get started.

**Additional context**
Here are at least two dependencies I needed to get by following the respective installations instructions:

for reference, i needed to follow these steps to install the dependencies.
may be worth adding some instructions to the build documentation

* openssl-sys: https://docs.rs/crate/openssl-sys/0.9.19
* libclang: https://rust-lang.github.io/rust-bindgen/requirements.html

**Comment by dr-frmr** [comment]
Finally added these to README, thanks.
