### ISSUE TITLE
bug: terminal piping is broken

### ISSUE THREAD

**Issue by tadad** [uqbar-dao/nectar#265]
**Describe the bug**
I believe this is due to changes in `Response`s. They used to be delivered even if the `Request` did not `expects_response`. Now, they are dropped if not. Piping relied on this old behavior. Need to think of a way to fix this

**To Reproduce**
`m our@kns_indexer:kns_indexer:sys {"NodeInfo":{"name":"goldfinger.os","block":299}}`
This command should print out in the terminal because it sends a response, but now it doesn't because the response to the terminal is dropped

**Comment by dr-frmr** [comment]
"fixed" by removing piping (for now?)
