### ISSUE TITLE
bug: terminal: pasting a command with a `\n` at end messes up cursor when scrolling thru previous commands

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#287]
**Describe the bug**
See title

**To Reproduce**
1. Copy a command, e.g., from Kinode book, with a newline at the end of it.
2. Paste into terminal.
3. <Enter>.
4. Scroll up to command history.
5. Note cursor is bound to far left until you hit <Backspace>.

**Expected behavior**
Not sure. Maybe show the line + newline with cursor on second line?

**Comment by dr-frmr** [comment]
fixed in #288
