### ISSUE TITLE
bug: many processes still prepend <process_name> to prints

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#290]
**Describe the bug**
Kernel now prepends process_id to prints, but many of our processes have not been updated to take advantage of this fact (so we get double prints).

**Expected behavior**
Just one process_id should be printed -- the kernel one. Remove the now-duplicated print from the processes.

**Comment by dr-frmr** [comment]
I can't find any examples of this, but we'll fix them as we find them

**Comment by dr-frmr** [comment]
pretty sure we got all of these in the system
