### ISSUE TITLE
bug: spams the optimism rpc on every keystroke

### ISSUE THREAD

**Issue by 0xlynett** [uqbar-dao/nectar#304]
**Describe the bug**
A keystroke in the password section of the Import Keyfile page causes multiple requests to be sent to the Optimism RPC.

**To Reproduce**
1. Start a new Kinode
2. Open 'Import Keyfile'
3. Open Network tab
4. Type into password input

**Expected behavior**
Typing should not affect requests being sent to the Optimism RPC.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop!_OS
 - Browser: Brave
 - Kinode version: 0.6.2

**Additional context**

**Comment by dr-frmr** [comment]
this has been fixed!
