### ISSUE TITLE
bug: app store doesn't scroll

### ISSUE THREAD

**Issue by dr-frmr** [uqbar-dao/nectar#307]
**Describe the bug**
If there are more apps than vertical screen space, the page clips in an ugly fashion and doesn't allow scrolling.

**To Reproduce**
- brave browser
- macOS
- app store with too many apps

**Expected behavior**
Should have padding above and below page content and a scroll bar.

**Screenshots**

<img width="1043" alt="Screenshot 2024-04-16 at 11 57 40 PM" src="https://github.com/kinode-dao/kinode/assets/93405247/c56f3de0-8e3c-4b6c-b805-c5ab7646a4dc">

**Comment by 0x70b1a5** [comment]
have we tried just not having that many apps?

**Comment by 0x70b1a5** [comment]
@dr-frmr in future, should i branch and PR for these issues, or commit to `develop`, if it's a one-liner like this one? (i just added a css class.)
