### ISSUE TITLE
feature: `vfs` should close files when possible

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#327]
**Is your feature request related to a problem? Please describe.**
`vfs` maintains a map of open files. There are a variety of operations that open a file and then do some thing to it, but don't need to maintain any state thereafter wrt to the file (e.g., reading the entire file, or getting the length, or getting the metadata). However, we almost never close files.

**Describe the solution you'd like**
If there isn't some ongoing operation wrt to the file, it should be closed after the operation.

**Comment by nick1udwig** [comment]
FYI @bitful-pannul -- I know you're occupied with other stuff, but this might be your wheelhouse sometime in the future.

**Comment by nick1udwig** [comment]
Am I right that you resolved this issue? @dr-frmr

**Comment by dr-frmr** [comment]
Yes, that's right. It's not ideal though, it's just a sweep to check for idle file handles and drop them. Could be better.

**Comment by nick1udwig** [comment]
Okay close or leave open this issue as you prefer
