### ISSUE TITLE
bug: import keyfile fails 

### ISSUE THREAD

**Issue by 0xlynett** [uqbar-dao/nectar#329]
**Describe the bug**
when trying to import a keyfile, it errors with `Request body deserialize error: missing field password_hash at line 1 column 602`. this is likely due to a field being changed on the frontend but not the validation endpoint

**To Reproduce**
1. Import keyfile
2. Fail

**Expected behavior**
Importing the keyfile successfully.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Kinode version 0.6.2 (also happens on later versions)

**Additional context**

request body looks like:
```
payload: <the keyfile here>
password: <the password hash here>
```
but it expects `password_hash` instead of `password`

**Comment by dr-frmr** [comment]
Thanks for this report. Definitely an oversight when we changed the field name a couple versions ago. Will be fixed in next release
