### ISSUE TITLE
ui feature: app 'downloading...' and 'installing...' modals are confusing

### ISSUE THREAD

**Issue by jurij-jukic** [uqbar-dao/nectar#330]
**Is your feature request related to a problem? Please describe.**

When I download or install an app, there is a modal which pops up. At first I wasn't sure if the download will continue if I click 'X', so  I was reluctant.

<img width="343" alt="downloading-modal" src="https://github.com/kinode-dao/kinode/assets/41450163/f964692b-6c71-43d7-a5cc-41e34db83501">

**Describe the solution you'd like**

For example, instead of using a modal, this button 'Download' could just say 'Downloading...'

<img width="912" alt="Screenshot 2024-05-06 at 10 02 47" src="https://github.com/kinode-dao/kinode/assets/41450163/4b52bf4c-dc14-4315-b8dc-8e3235f1a150">

This button here could also say 'Downloading...':
<img width="913" alt="Screenshot 2024-05-06 at 10 10 17" src="https://github.com/kinode-dao/kinode/assets/41450163/2e933130-047b-4af5-b517-df39a69faf54">

And analogously for installs,
here:
<img width="915" alt="Screenshot 2024-05-06 at 10 08 20" src="https://github.com/kinode-dao/kinode/assets/41450163/14fb42fd-f342-4542-a91c-9e907ae7232f">
and here:
<img width="922" alt="Screenshot 2024-05-06 at 10 09 07" src="https://github.com/kinode-dao/kinode/assets/41450163/ee1f0551-65f1-45d1-896c-e2b69d2c6989">

**Comment by 0x70b1a5** [comment]
#372
