### ISSUE TITLE
ui: using an app

### ISSUE THREAD

**Issue by jurij-jukic** [uqbar-dao/nectar#331]
**Is your feature request related to a problem? Please describe.**
As a user, I have no idea how to use an app. There is no 'open app' button. If there is a different way to do it, there are no instructions in the App Store.

I specifically needed to find youtube videos in order to figure out how to use apps, e.g. for [Barter](https://www.youtube.com/watch?v=DLxgQG1RWKI) or [Filter](https://www.youtube.com/watch?v=w1hkFeTTcxg), which no user can be expected to find by themselves.

**Describe the solution you'd like**
- an 'open app' button
- an `instructions` field in the app metadata which will prompt devs to link to youtube tutorials or write down the instructions.

**Describe alternatives you've considered**
- somehow asserting a strong convention that instructions should be written down in the `Description` field

**Comment by dr-frmr** [comment]
Fixed in next release, will close when we merge to main
