### ISSUE TITLE
bug: after clicking 'reset networking info' going back doesn't work

### ISSUE THREAD

**Issue by jurij-jukic** [uqbar-dao/nectar#333]
**Describe the bug**
After I click on 'Reset Networking Info' in the login page, going back to the regular login page is not possible.

**To Reproduce**
1. Go to login page
2. Click on 'Reset Networking Info' 
<img width="490" alt="Screenshot 2024-05-06 at 11 55 41" src="https://github.com/kinode-dao/kinode/assets/41450163/0c4ca16c-3de1-4f12-927e-1dbd5e4a5061">

3. Get here
<img width="527" alt="Screenshot 2024-05-06 at 12 01 08" src="https://github.com/kinode-dao/kinode/assets/41450163/70012a93-9723-4d32-8c36-f53bef89b949">

4. Click 'Go Back' in your browser, it doesn't work.

**Expected behavior**
Should be able to navigate back to the previous url.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Arc (Chromium based), Safari
 - Kinode version v0.7.0
 - process_lib version v0.7.0 (based on Cargo.lock, but there is a bunch of these, so not sure which exactly am I supposed to refer to)

**Comment by 0x70b1a5** [comment]
Fixed in #323
