### ISSUE TITLE
feature: delete key in terminal

### ISSUE THREAD

**Issue by 0xlynett** [uqbar-dao/nectar#361]
**Is your feature request related to a problem? Please describe.**
Sometimes I naturally reach for the Delete key to delete my input from the terminal but am forced to use backspace instead.

**Describe the solution you'd like**
Add the intuitive Delete key behavior: to delete the character to the right of the cursor.

**Describe alternatives you've considered**
- Just using backspace

**Additional context**
None needed, simple quality of life improvement for devs

**Comment by dr-frmr** [comment]
fixed with #378
