### ISSUE TITLE
bug: ports still taken after ungraceful exit

### ISSUE THREAD

**Issue by jurij-jukic** [uqbar-dao/nectar#403]
**Describe the bug**
every once in a while my kinode gets stuck (when runtime panics) and i cannot exit gracefully with ctrl+z, ctrl+c or ctrl+d. so i kill the terminal in those situations. however when i boot my kinode again, then the previous port (i.e. 8080) is still taken and i cannot kill it unless i rebooot my pc.

check out the [conversation on discord](https://discord.com/channels/1186394868336038080/1186421052071477428/1251380412685488241) when i encountered a bunch of taken ports (what i realized later was from kinode panicing and me having to ungracefully exit)

**To Reproduce**
1. make your kinode panic
2. try to exit with ctrl+c, you won't be able to
3. kill terminal
4. run `ps -ef | grep kinode` to see taken ports

**Comment by dr-frmr** [comment]
The real issue we need to fix here is the runtime panic case -- after an ungraceful exit, there's nothing we can do about the ports being still taken on your system. We'll handle the panic cases as we find them.
