### ISSUE TITLE
bug: connectivity issue when rebooting 1 fake node but not the other

### ISSUE THREAD

**Issue by jurij-jukic** [uqbar-dao/nectar#405]
```
fake.dev > hi fake2.dev "hi"
Mon 10:16 terminal:sys: fake2.dev is offline or does not exist
```

fake nodes cannot connect after one of them has been rebooted. to make them connect, you need to reboot both.

**Comment by nick1udwig** [comment]
The first node manages the mock network, and so if it is brought down, it is expected that other nodes will no longer be able to communicate without restarting the whole network.
