### ISSUE TITLE
feature: document terminal script to kill a process (and others yet undocumented)

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#413]
https://discord.com/channels/1186394868336038080/1186421052071477428/1252741084208169132

**Comment by nick1udwig** [comment]
https://discord.com/channels/1186394868336038080/1186421052071477428/1252742745479450717

**Comment by nick1udwig** [comment]
https://github.com/kinode-dao/kinode?tab=readme-ov-file#terminal-syntax

**Comment by dr-frmr** [comment]
Just did this on `develop`.
