### ISSUE TITLE
bug: system doesnt recognize caps after a bad terminal command

### ISSUE THREAD

**Issue by jurij-jukic** [uqbar-dao/nectar#416]
**Describe the bug**

- a bunch of messages of this kind start popping up for various permutations of processes:
```
Wed 15:53 event loop: process http_server:distro:sys doesn't have capability to message process main:command_center:appattacc.os
```

- my guess is that this starts happening after running a command which inputs the wrong type. i.e. worker_address here is supposed to be an Address, but i am inputting a string:
```
m astronaut.os@main:command_center:appattacc.os '{"BackupRetrieve": {"node_id": "sour-cabbage.os", "worker_address":""}}'
```

so you can probably recreate this with any app you are working by simply inputting a wrong type. but maybe i'm wrong and if something else is the cause, here is how to reproduce.

**To Reproduce**
1. install the following commit of [command center](https://github.com/kinode-dao/command_center/pull/1/commits/5fe9847ea7e993c12a61d3307f0b2647c5458995
) on your kinode 
2. run the command:
```
m astronaut.os@main:command_center:appattacc.os '{"BackupRetrieve": {"node_id": "sour-cabbage.os", "worker_address":""}}'
```
3. a bunch of previously successful caps will stop working

**Comment by nick1udwig** [comment]
https://discord.com/channels/1186394868336038080/1186421052071477428/1253186534266507367
https://discord.com/channels/1186394868336038080/1186421052071477428/1253187341045072044

**Comment by dr-frmr** [comment]
Working on this

**Comment by dr-frmr** [comment]
@nick1udwig @jurij-jukic check out #427

**Comment by nick1udwig** [comment]
#427 fixed this
