### ISSUE TITLE
feature: redirect login from an app page back to that app page after login

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#429]
See #425. PR #428 fixes the bug by redirecting from app login to node login, but user must then navigate back to app endpoint. A better behavior would be to, after login, redirect back to app endpoint.

**Comment by gtimoth** [comment]
@nick1udwig request to also do this for URL params. Note that URL params are currently lost in two scenarios:
1. when logging in
2. when redirected to secure subdomain, e.g. `baseorigin.com/app:pkg:dev.os/?param=foo` -> `pkg-dev-os.baseorigin.com/app:pkg:dev.os`

This is an important feature for dartfrog.

**Comment by nick1udwig** [comment]
#439 merged
