### ISSUE TITLE
bug: killing a process does not execute its OnExit

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#430]
**Describe the bug**
When a process is Killed, its OnExit is not respected.

**Expected behavior**
Do OnExit on kill, if at all possible.

**How**
First, try to kill nicely. This should always work. If that fails, do the current method.

How to kill nicely?

1. Add a new channel to each process. This is the "kill channel": a send on it kills the process.
2. The receiver sits in a `select!` next to [`call_init`](https://github.com/kinode-dao/kinode/blob/3719ab38e19143a7bcd501fd245c7a10b2239ee7/kinode/src/kernel/process.rs#L316-L318)
3. When received, the `select!` falls through.

**Comment by nick1udwig** [comment]
https://discord.com/channels/1186394868336038080/1186684706700410962/1250586206463594577

**Comment by dr-frmr** [comment]
One possible solution that would be really good, if it is truly possible:

Moving this code from where it is, in the process task
https://github.com/kinode-dao/kinode/blob/aa100725c0873971e7e696cabb02e110ce9d410f/kinode/src/kernel/process.rs#L347-L348

To in here:
https://github.com/kinode-dao/kinode/blob/aa100725c0873971e7e696cabb02e110ce9d410f/kinode/src/kernel/mod.rs#L367

**Comment by nick1udwig** [comment]
I'm not sure I agree. What if a process exits normally? Does `Kill` still get called? I also do like that we currently have the entire "process lifecycle" in one place. Very easy to read & reason about.

**Comment by nick1udwig** [comment]
I'm no longer convinced that this is a bug. Looking at how we use KillProcess, it is only ever an outside intervention to bring a process down, e.g., a `kill` from `terminal` or `settings`,, the `app_store` `Uninstall`ing a process, or something of the like. Need to think more about this before changing the behavior. I'll leave the issue open for now.

https://github.com/search?q=repo%3Akinode-dao%2Fkinode%20KillProcess&type=code

**Comment by dr-frmr** [comment]
@nick1udwig should we close this? We've determined in a few conversations that this is the desired behavior

**Comment by nick1udwig** [comment]
The remaining question here is https://discord.com/channels/1186394868336038080/1186421052071477428/1265348617493811200

Was the resolution to push it up one level? I.e. add a less-aggressive `Stop` in some sort of app framework that is more respectful & will honor OnExit or whatever equivalent occurs at that level?

**Comment by dr-frmr** [comment]
Yes, I think so. A process that can be respectfully stopped should expose a call in its request-response protocol that does so, and permission it as desired.
