### ISSUE TITLE
bug: ui error when getting new version of memedeck

### ISSUE THREAD

**Issue by Tenari** [uqbar-dao/nectar#437]
**Describe the bug**
UI Error updating memedeck app immediately after new version is published

**To Reproduce**
1. I publish new memedeck app from app store (btw new version is out)
2. I open my personal kinode right away and try to install the update
3. click on app store
4. click on the little ! icon in the corner of the memdeck app, am taken to the info page
5. it says there's a new version out, I click Update.
6. Approve and Install
7. Error failed to update

but now if I wait a moment (for the package zip file to install) and navigate back to the app store I see a capital "I" icon in the top corner of the Memedeck app, which when I click, successfully lets me install the new memedeck version.

I can see that the memedeck app is big and takes a while to share, so perhaps that's part of this error? like the ui just isn't handling the case where it knows about a new update but doesn't have it downloaded yet? I'm not sure. lmk if you need more info, or if I should file this issue somewhere else
`Tue 14:42 app_store:sys: successfully shared /memedeck:meme-deck.os.zip in 40.6802s`

**Expected behavior**
from the ui I expected to be able to click "Update" then "approve and install" and not get an error message

**Screenshots**
here is the in-order slide show of what I saw/clicked on:

<img width="561" alt="Screenshot 2024-07-11 at 10 07 50 AM" src="https://github.com/kinode-dao/kinode/assets/3653835/30831dd0-cb56-4158-9ab1-471f602554e3">
<img width="1114" alt="Screenshot 2024-07-11 at 10 07 57 AM" src="https://github.com/kinode-dao/kinode/assets/3653835/e34809ff-5dbe-46c0-85e4-f79466883f32">
<img width="449" alt="Screenshot 2024-07-11 at 10 08 04 AM" src="https://github.com/kinode-dao/kinode/assets/3653835/6896709c-bc6c-40a4-a424-c8710a185f52">
<img width="531" alt="Screenshot 2024-07-11 at 10 08 11 AM" src="https://github.com/kinode-dao/kinode/assets/3653835/cb6eec83-a21c-49e3-ad43-b328e8a01190">

then I clicked the back arrow to go to the app store again

<img width="645" alt="Screenshot 2024-07-11 at 10 08 25 AM" src="https://github.com/kinode-dao/kinode/assets/3653835/c0f77433-c602-4954-a9e0-70ab0bd1c08e">
<img width="1056" alt="Screenshot 2024-07-11 at 10 08 32 AM" src="https://github.com/kinode-dao/kinode/assets/3653835/6b2697e5-3d20-432e-816e-3491f6b84bf3">
<img width="509" alt="Screenshot 2024-07-11 at 10 08 39 AM" src="https://github.com/kinode-dao/kinode/assets/3653835/d18b6c97-efb7-4e75-beec-075684c82f9b">
<img width="1017" alt="Screenshot 2024-07-11 at 10 08 48 AM" src="https://github.com/kinode-dao/kinode/assets/3653835/e0c88509-993e-4807-aa03-8e6acfd84470">

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: brave
 - Kinode version: meme-deck.os (direct) is running runtime version 0.8.1

**Comment by dr-frmr** [comment]
@Tenari I will get this fixed, but as a side note, can you review the package and see if there are extra files tucked away somewhere? how big is it, in megabytes, that a download takes that long?

**Comment by dr-frmr** [comment]
closing as we've totally redone the UI since this
