### ISSUE TITLE
bug: can't import keyfile (0.8.3)

### ISSUE THREAD

**Issue by 0x70b1a5** [uqbar-dao/nectar#448]
**Describe the bug**
I cannot import a keyfile to a fresh node.

**To Reproduce**
1. Export your .keys from a node, `node1`.
2. Boot a fresh node at a new folder, `node2`.
3. Open browser and select your .keys file to import.
4. See error. Console reads 404 at /vet-keyfile.

**Expected behavior**
It should let me boot `node2` with the same identity as `node1`.

**Screenshots**
![image](https://github.com/user-attachments/assets/401b52b8-a158-45cf-b98c-089f5622b2bb)

**Desktop (please complete the following information):**
 - OS: MacBook Pro 2017, Ventura 13.6.7
 - Browser Brave
 - Kinode version 0.8.3
 - process_lib version unk

**Additional context**

**Comment by dr-frmr** [comment]
fixed in #451
