### ISSUE TITLE
bug: logging into a fakenode before "fakenode - any password will work!" reloads the page and puts the password into the URL bar

### ISSUE THREAD

**Issue by 0x70b1a5** [uqbar-dao/nectar#476]
**Describe the bug**
You have to wait for the "any password" message to show up before submitting the login form, else the login POST reloads the page with the text you entered clearly visible in the URL bar as `?password=yourmaybesecurepass`.

**To Reproduce**
1. `kit f`
2. open http://localhost:8080 
3. enter password quickly and hit enter
4. verify page reloads and password is visible 

**Expected behavior**
either prevent login until the page is ready, or submit it in a different way that can make the login happen as soon as the field is rendered

**Desktop (please complete the following information):**
 - OS: mac os ventura 13.6.7
 - Browser brave
 - Kinode version 0.8.6

**Comment by dr-frmr** [comment]
fixed in #485 i hope! i'll leave this open until you can use 0.9.0 and confirm it resolves the issue for you @0x70b1a5

**Comment by dr-frmr** [comment]
@0x70b1a5 when you get a moment can you confirm that this issue has been fixed in 0.9.2?

**Comment by dr-frmr** [comment]
Taking this down as fixed
