### ISSUE TITLE
bug: builds are not reproducible

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#509]
**Describe the bug**
Building with `--release` and then doing it again produce builds with different hashes.

**To Reproduce**
^

**Expected behavior**
Same hash

**Additional context**
Almost certainly a timestamping in one of the zips/tars we are including in the build binary.

**Comment by dr-frmr** [comment]
Fixed now?

**Comment by nick1udwig** [comment]
Yup. Github used to autoclose when you put `resolves #f00` in PR text, but seems they broke it
