### ISSUE TITLE
bug: "Launch" button appears for all apps in appstore regardless of installation status or presence of app web UI

### ISSUE THREAD

**Issue by 0x70b1a5** [uqbar-dao/nectar#515]
**Describe the bug**
Launch button is always visible. 

**To Reproduce**
1. On a fresh node, go to any non-installed app page in the appstore.
2. Confirm Launch button is showing.

**Expected behavior**
Launch button should display IFF app is installed && app has web UI.

**Comment by nick1udwig** [comment]
Not sure if this is same or different bug, but after installing a no-web-UI app, I see spamming:
```
Tue 16:06 http_server: got request for path /main:app_store:sys/apps/chat:template.os
Tue 16:06 http_server: got request for path /main:app_store:sys/installed/chat:template.os
Tue 16:06 http_server: got request for path /main:app_store:sys/downloads/chat:template.os
```

**Comment by nick1udwig** [comment]
I think its a separate bug; opening a new issue
