### ISSUE TITLE
feature: gracefully handle `-`s vs `_`s in wasm filenames

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#527]
**Is your feature request related to a problem? Please describe.**
https://github.com/kinode-dao/kit/issues/216 documents annoyance of cargo preferring `_`s and Kimap App Store protocol preferring `-`s. https://github.com/kinode-dao/kit/pull/222 resolved this on the `kit` side by making `kit` more robust wrt `_`s vs `-`s and just "doing the right thing". There is still some trickiness here associated with our `manifest.json` files, where we specify a file path for processes.

**Describe the solution you'd like**
Make Kinode core, when given a process path of `foo-bar.wasm`, if not found, check for `foo_bar.wasm` (and vice versa!). Print a verbosity 1 message if this switcheroo happens so that devs can be informed.

Ideally this should happen for both `manifest.json`, `scripts.json`, and `spawn()` to give a consistent behavior across all process-spawning interfaces.

**Describe alternatives you've considered**
This is in addition to `kit` being better. E.g., `kit` could read `manifest.json` and see if the corresponding `.wasm` file exists; error out with useful error message if it does not.

**Additional context**
@dr-frmr what do you think about this?

**Comment by dr-frmr** [comment]
Yup, ought to do this

**Comment by dr-frmr** [comment]
Revisiting this @nick1udwig I am now thinking that we should strictly enforce non-usage of underscore. Otherwise, every program that wants to interact with .wasm files stored in the VFS will always need to implement this backup-check logic. It seems burdensome as opposed to following the config files blindly and immediately alerting the developer if they are misconfigured.

**Comment by nick1udwig** [comment]
Hmm, yeah, its either every `.wasm` interaction has the backup logic or else fail out ASAP.

I can change `kit` to error out given `_`s. This would be a breaking change.

**Comment by nick1udwig** [comment]
https://github.com/kinode-dao/kit/pull/257 implements the desired "fail fast" behavior in `kit`.

At a minimum we should change distro modules/processes to use `-`s rather than `_`s. This would be a breaking change unless we alias them.

We should also consider rejecting running `.wasm` files that have a `_` in them. This would be a breaking change as well.

**Comment by dr-frmr** [comment]
Is this work done / can we close this? @nick1udwig

**Comment by nick1udwig** [comment]
Yup -- just waiting on 0.10.0 to merge, but work is done
