### ISSUE TITLE
Globe Widget Spams Log with Rate Limited Errors

### ISSUE THREAD

**Issue by jaxs-ribs** [uqbar-dao/nectar#531]
**Describe the bug**

When booting a node in some locations (for example SE Asia?), we get 
```
Mon 21:46 kino_updates:sys: Failed to parse location: Object {"error": Bool(true), "message": String("Visit https://ipapi.co/ratelimited/ "), "reason": String("RateLimited")}
```

**To Reproduce**
Unclear, some nodes work, others don't 

**Expected behavior**
Less log spam at least, to make debuggin things on this node easier.

**Comment by dr-frmr** [comment]
No such thing as a free lunch...

I'll add a failure tracker that instructs the widget to give up if it can't get a response from the API in a few tries. Sorry about that. Can `uninstall:app_store:sys kino_updates:sys` as needed for now.

**Comment by dr-frmr** [comment]
Limit added

**Comment by abdullahdevrel** [comment]
I have created this feature request ticket pitching IPinfo: https://github.com/kinode-dao/kinode/issues/555

IPinfo provides up to 1,000 requests per day without any access token from individual unique IP addresses.
