### ISSUE TITLE
bug: app_store FE publish flow doesn't stop user from publishing invalid name (i.e. `_`s

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#537]
**Describe the bug**
App Store FE publish flow must only allow valid names

https://discord.com/channels/1186394868336038080/1186421052071477428/1284265608103333978

**Comment by nick1udwig** [comment]
Here's what we need to check: https://github.com/kinode-dao/kit/blob/master/src/publish/mod.rs#L107-L109

**Comment by barraguda** [comment]
> **Describe the bug** App Store FE publish flow must only allow valid names

there is a warning on FE if package_name includes "_" or other invalid characters:

<img width="569" alt="Screenshot 2024-09-17 at 15 33 58" src="https://github.com/user-attachments/assets/b425fef0-21d7-4ae3-998a-29116e350a65">

It should block the publish button
