### ISSUE TITLE
feature: Using IPinfo.io for IP information (IP Geolocation + ASN)

### ISSUE THREAD

**Issue by abdullahdevrel** [uqbar-dao/nectar#555]
**Is your feature request related to a problem? Please describe.**

I would like to recommend ipinfo.io for IP data. 

- Provides highly accurate IP geolocation backed by our probe network infrastructure.
- Free tier access token supports 50,000 requests per month.
- IPinfo supports HTTPS/SSL encryption on all endpoints.
- Tokenless access grants 1,000 requests per day to each unique IP address.
- No rate limit for repeated API requests. You can make all the allocated requests in one go. 
- Includes ASN and hostname information. Supports bulk enrichment through a single API endpoint. We also have a comprehensive integration library.

**Describe the solution you'd like**

I would recommend using IPinfo's API service.

Usage example:

```
curl https://ipinfo.io/8.8.8.8
```

```
{
    "ip": "8.8.8.8",
    "hostname": "dns.google",
    "anycast": true,
    "city": "Mountain View",
    "region": "California",
    "country": "US",
    "loc": "37.4056,-122.0775",
    "org": "AS15169 Google LLC",
    "postal": "94043",
    "timezone": "America/Los_Angeles"
}
```

Documentation: https://ipinfo.io/developers

**Describe alternatives you've considered**

I have not considered any alternatives.

**Additional context**

None.

---

Consider including IPinfo in the project for accurate data and generous free access. Please let me know what you think. Thank you very much.

**Comment by dr-frmr** [comment]
Thanks for the suggestion. I will add it as a backup option to our little program.
