### ISSUE TITLE
feature: add caps to `m` from terminal

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#579]
**Is your feature request related to a problem? Please describe.**
Can't use `m` to make requests that require an attached capability.

**Describe the solution you'd like**
We should allow the user to specify the capability to attach to the request.

Perhaps automagically attach all caps that were issued by `foo:bar:baz.os` when sending a request to `foo:bar:baz.os`. I don't think we currently expose this information to processes, however.

**Comment by dr-frmr** [comment]
I mean, this is a necessary restriction of the security model. The terminal can only attach capabilities to `m` that the terminal itself has. If a process doesn't want to give the terminal messaging capabilities, `m` cannot be used. If a process does want to make sure `m` can be used, it can just grant necessary capabilities to the terminal, which (I think) will pass them all on to `m`.

If a process wants to be usable as a CLI without giving capabilities to the terminal, it should include in its package 1 or more scripts that can be used with it. Those scripts can be granted various capabilities in `scripts.json`.

**Comment by nick1udwig** [comment]
Hmm, yeah, good point. In #596 I modified `m` to attach all caps `terminal` has for the target process.

However, as noted there, there's still an issue. Userspace caps can't be granted to `terminal`, and hence `m` cannot inherit them. Two proposed ways to get around this are:
1. Change manifest field `grant_capabilities` to allow non-`messaging` caps to be granted,
2. Add a `terminal:terminal:sys` api that allows processes to give it capabilities.

**Comment by nick1udwig** [comment]
done; see #581 for relevant PRs
