### ISSUE TITLE
feature: print process, not just package, on print

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#583]
https://discord.com/channels/1186394868336038080/1186421052071477428/1298984922840698881

**Comment by dr-frmr** [comment]
I lean towards package because the full process ID takes up so much screen real estate. At the package level, we can be certain that the developer has control over their prints -- if they want to specify the process, they can easily do that in the print itself, no?

**Comment by jurij-jukic** [comment]
i think you are right. but it is still tedious to write in every print "process-name: print text".

is it possible to have a custom print macro which will print a process name in front of every print?

**Comment by dr-frmr** [comment]
https://github.com/kinode-dao/process_lib/pull/117/commits/75d3f108c1bd40410263fd50b5c383f5f5f7df2a

added to process_lib!
