### ISSUE TITLE
feature: process not found prints to debug(1) instead of (0)

### ISSUE THREAD

**Issue by barraguda** [uqbar-dao/nectar#585]
**Is your feature request related to a problem? Please describe.**
https://discord.com/channels/1186394868336038080/1186421052071477428/1299328371943280713

Got request from network but process X doesn't exist can happen often, for example in the case of uninstalling an app, and still getting network requests from it. These will be discarded by the kernel but their verbosity is very high right now.

**Describe the solution you'd like**
Perhaps a config? Or just put in them in verbosity 1 or 2.

**Additional context**

Code links where this happens:
https://github.com/kinode-dao/kinode/blob/8ef4fbcacddb35429727d5b8725e7a402b2ebb3e/kinode/src/kernel/mod.rs#L803-L826

**Comment by nick1udwig** [comment]
#586
