### ISSUE TITLE
feature register-ui: mint already committed name

### ISSUE THREAD

**Issue by barraguda** [uqbar-dao/nectar#600]
**Is your feature request related to a problem? Please describe.**
If I commit to a .os name, I've observed with bad network conditions that even if the tx goes through, the FE wallet code doesn't necessarily index that, and stays on the commit page. 

That's all fine, but if I refresh, and enter the name again I get a chain error back instead of being redirected to the correct spot.

**Describe the solution you'd like**
Either change /mint-os-name to take a url param or query param of which name it wants to mint, instead of or in addition to the current react props being passed. 

**Describe alternatives you've considered**
If we can, we should do 1 extra contract call upon clicking mint, check for a commitment from connected_wallet_address. Then we can forward directly to the mint_page instead of the commit one.

**Comment by dr-frmr** [comment]
> Describe alternatives you've considered
> If we can, we should do 1 extra contract call upon clicking mint, check for a commitment from connected_wallet_address. > Then we can forward directly to the mint_page instead of the commit one.

Yeah, been thinking we should just prompt the txn instead of having a "mint" button after the "commit" one. I will try to merge the buttons.

**Comment by dr-frmr** [comment]
I merged the buttons
