### ISSUE TITLE
feature: make widget settings modal look nicer

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#604]
**Is your feature request related to a problem? Please describe.**
When you click into "widget settings" the entire background turns white.

**Describe the solution you'd like**
Have the modal be a normal modal: appear to be hovering over the page.

![image](https://github.com/user-attachments/assets/fb9b89bb-4eb5-420e-9caa-ae5fb25d8a1a)
![image](https://github.com/user-attachments/assets/e585cfcb-9ad6-42b3-9c16-e27ebf7a83d6)

**Comment by dr-frmr** [comment]
fixed with [2b7990f](https://github.com/kinode-dao/kinode/pull/609/commits/2b7990fb144017f6bdeca42a67915f02c1fcf8f0)
